name: dolo_env
dependencies:
- alabaster=0.7.7=py35_0
- babel=2.2.0=py35_0
- docutils=0.12=py35_0
- fastcache=1.0.2=py35_0
- jinja2=2.8=py35_0
- llvmlite=0.8.0=py35_0
- markupsafe=0.23=py35_0
- mkl=11.3.1=0
- numba=0.23.1=np110py35_0
- numexpr=2.5=np110py35_0
- numpy=1.10.4=py35_0
- numpydoc=0.5=py35_1
- openssl=1.0.2f=0
- pandas=0.17.1=np110py35_0
- pip=8.0.3=py35_0
- pygments=2.1.1=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- readline=6.2=2
- setuptools=20.1.1=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.3.5=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- sqlite=3.9.2=0
- sympy=0.7.6.1=py35_0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - sphinx-better-theme==0.13
  - sphinx-rtd-theme==0.1.9

