name: dolo_env
dependencies:
- numba
- numexpr
- numpy
- numpydoc
- pandas
- pip
- pygments
- ipython
- python=3.5.1=0
- pyyaml=3.11
- sphinx_rtd_theme
- sympy
- xarray
- scipy
# - pip:
#   - sphinx-better-theme==0.13
