name: dolo_env
dependencies:
- ipython
- numba
- numexpr
- numpy
- numpydoc
- pip
- pandas
- pygments
- python=3.5.1=0
- pyyaml=3.11
- scipy
- sphinx_rtd_theme
- sympy
- statsmodels
- matplotlib
- xarray
# - pip:
#   - sphinx-better-theme==0.13
